name: platform_ui
description: Platform specific design system with wide collection of UI widgets
version: 0.1.0
homepage: https://github.com/KRTirtho/platform_ui

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  fluent_ui: ^4.0.2
  macos_ui: ^1.7.5
  libadwaita: ^1.2.5
  adwaita: ^0.5.2
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0